spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/mariadb
    username: malldbuser
    password: malldbuser

  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true